# 最后在 Python 中

> 原文:[https://www.educba.com/finally-in-python/](https://www.educba.com/finally-in-python/)

![Finally in Python](../Images/86ff2503b9685ac385ad2c886f6e5e67.png)

<noscript><img class="alignnone size-full wp-image-381149" src="../Images/86ff2503b9685ac385ad2c886f6e5e67.png" alt="Finally in Python" width="900" height="500" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/06/template-10-2.jpg 900w, https://cdn.educba.com/academy/wp-content/uploads/2020/06/template-10-2-300x167.jpg 300w, https://cdn.educba.com/academy/wp-content/uploads/2020/06/template-10-2-768x427.jpg 768w" sizes="(max-width: 900px) 100vw, 900px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/06/template-10-2.jpg"/></noscript>

## Python 中的 Finally 简介

有时，当前正在运行的方法可能会突然终止，试图处理编程中的一些异常，但该方法需要在终止前完成一些活动，如关闭网络或关闭打开的文件等，为了处理这种情况，python 中提供了一个名为 finally 的关键字，它是在执行 try 代码块之后执行的代码块，但不包括块 这个最后的代码块通常在 try 代码块执行之后或者由于某种异常而终止之后执行。

**语法:**

<small>网页开发、编程语言、软件测试&其他</small>

Python 中 Finally 关键字的语法如下:

```
try:
 {
 //Block of code
}
except:
 {
//Block of code
// this can be optional
//Exception handling, if necessary

}
finally:
{
    //Block of code which is always executed
} 
```

### Python 中 Finally 关键字的功能

*   每当当前方法突然终止时，该方法可能一直在使用分配给它的资源，并且在当前方法终止时不会被释放或关闭。
*   在这种情况下，最后一个代码块用于释放 try 代码块中分配的资源，无论 except 代码块是否处理异常，最后一个代码块总是被执行。
*   如果在控制项离开 try 程式码区块后，例外的程式码区块未处理例外状况，则在 finally 程式码区块执行完成后，会再次引发例外状况。
*   需要释放的系统资源由 finally 代码块完成。
*   最后，可以在没有 except 代码块的情况下，在 try 代码块之后使用代码块，但是不会处理将要引发的异常。

### Python 中 Finally 的示例

下面是一些例子:

#### 示例#1

Python 程序演示了 Finally 代码块在程序中的使用，其中异常由 except 代码块处理:

**代码:**

```
#python program to demonstrate finally block
#try and except blocks to handle the exception
try: 
    #divide by zero exception will be raised
    r = 10//0  
    print(r) 
#divide by zero exception is handled here     
except ZeroDivisionError:    
    print("The divisor cannot be zero")   
#finally block of code which will always be executed regardless of the exception is handled or not
finally: 
    print('This is finally block of code which is always executed regardless of the exception is handled or not.') 
```

**输出:**

![Finally in Python-1.1](../Images/10bffb7c7f236c303c2093207a32a6f9.png)

<noscript><img class="alignnone size-full wp-image-380814" src="../Images/10bffb7c7f236c303c2093207a32a6f9.png" alt="Finally in Python-1.1" width="651" height="107" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/06/Finally-in-Python-1.1.png 651w, https://cdn.educba.com/academy/wp-content/uploads/2020/06/Finally-in-Python-1.1-300x49.png 300w" sizes="(max-width: 651px) 100vw, 651px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/06/Finally-in-Python-1.1.png"/></noscript>

**代码解释:**在上面的程序中演示 finally 块、try 块和 except 块的代码都用来处理被零除的异常。变量 r 用于存储 10/0 的除法结果，因为除数不能为零，所以不能这样做。因此，except 块引发了一个异常，它说除数不能为零，然后执行最后一个代码块，不管异常是否被处理，这个代码块都会被执行。程序的输出显示在上面的快照中。

#### 实施例 2

Python 程序演示了 finally 关键字在程序中的用法，在该程序中，异常由(代码块除外)处理:

**代码:**

```
#python program to demonstrate finally block
#try and except blocks to handle the exception
try: 
    #no exception will be raised
    r = 10//10  
    print(r) 
#divide by zero exception is handled here in case if it happens     
except ZeroDivisionError:    
    print("The divisor cannot be zero") 
#finally block of code which will always be executed regardless of the exception is raised or not or if it is raised, regardless of it is handled or not
finally: 
print('This is finally block of code which is always executed regardless of the exception is raised or not or if it is raised, regardless of it is handled or not.') 
```

**输出:**

![Example-1.2](../Images/c6c6a9d5fdcc3fd7898b4398e9d0e783.png)

<noscript><img class="alignnone wp-image-380815 size-full" src="../Images/c6c6a9d5fdcc3fd7898b4398e9d0e783.png" alt="Example-1.2" width="786" height="88" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/06/Finally-in-Python-1.2.png 786w, https://cdn.educba.com/academy/wp-content/uploads/2020/06/Finally-in-Python-1.2-300x34.png 300w, https://cdn.educba.com/academy/wp-content/uploads/2020/06/Finally-in-Python-1.2-768x86.png 768w" sizes="(max-width: 786px) 100vw, 786px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/06/Finally-in-Python-1.2.png"/></noscript>

**代码解释:**在上面演示 finally 块的程序中，try 和 except 代码块用于处理被零除的异常(如果出现的话)。变量 r 用于存储 10/10 的除法结果，其结果为 1 而不会引起任何异常。因此，不执行 except 代码块，即除数不能为零，然后执行最后一个代码块，该代码块将始终被执行，而不管异常是否被引发，如果被引发，也不管异常是否被处理。程序的输出显示在上面的快照中。

#### 实施例 3

演示 finally 关键字在没有异常处理的程序中的用法的 C#程序:

**代码:**

```
#python program to demonstrate finally block
#try and except blocks to handle the exception
try: 
    #divide by zero exception is expected
    r = 10//0  
    print(r)   
#finally block of code which will always be executed regardless of the exception is handled or not
finally:  
    print('This is finally block of code which is always executed regardless of the exception is raised or not or if it is raised, regardless of it is handled or not.') 
```

**输出:**

![Example-1.3](../Images/def9ba8494b3f72b452b53853999df05.png)

<noscript><img class="alignnone wp-image-380816 size-full" src="../Images/def9ba8494b3f72b452b53853999df05.png" alt="Example-1.3" width="791" height="154" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/06/Finally-in-Python-1.3.png 791w, https://cdn.educba.com/academy/wp-content/uploads/2020/06/Finally-in-Python-1.3-300x58.png 300w, https://cdn.educba.com/academy/wp-content/uploads/2020/06/Finally-in-Python-1.3-768x150.png 768w" sizes="(max-width: 791px) 100vw, 791px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/06/Finally-in-Python-1.3.png"/></noscript>

**代码解释:**在上面演示 finally 块的程序中，使用了 try 代码块，其中变量 r 用于存储 10/0 的除法结果，这是不可能的，会导致异常。但是我们没有定义 except 代码块来处理异常。因此，没有异常处理，然后执行最后一个代码块，无论是否引发异常，如果引发了异常，无论异常是否被处理，该代码块都会被执行。程序的输出显示在上面的快照中。

### 推荐文章

这是 Python 中的 Finally 指南。在这里，我们还将讨论 python 中 finally 关键字的介绍和工作原理，以及不同的示例和代码实现。您也可以看看以下文章，了解更多信息–

1.  [Python 计数器](https://www.educba.com/python-counter/)
2.  [Python 并发](https://www.educba.com/python-concurrency/)
3.  [Python 排序数组](https://www.educba.com/python-sort-array/)
4.  [Python 中的控制语句](https://www.educba.com/control-statements-in-python/)

<footer class="entry-footer">

<aside class="sidebar sidebar-primary widget-area" role="complementary" aria-label="Primary Sidebar">Primary Sidebar</aside>

</footer>