# 最后在 Java 中

> 原文:[https://www.educba.com/finally-in-java/](https://www.educba.com/finally-in-java/)

![Finally in Java](../Images/0beadc02fe9111af7a874047f59e9634.png)

<noscript><img class="alignnone size-full wp-image-322277" src="../Images/0beadc02fe9111af7a874047f59e9634.png" alt="Finally in Java" width="900" height="500" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/03/Finally-in-Java.jpg 900w, https://cdn.educba.com/academy/wp-content/uploads/2020/03/Finally-in-Java-300x167.jpg 300w, https://cdn.educba.com/academy/wp-content/uploads/2020/03/Finally-in-Java-768x427.jpg 768w" sizes="(max-width: 900px) 100vw, 900px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/03/Finally-in-Java.jpg"/></noscript>

## Java 中的 Finally 简介

下面的文章提供了 Java 中 Finally 的概要。最后，是与 try and catch 一起使用的代码块。最后包含无论异常是否发生都必须执行的代码块。无论 try 块中是否出现错误，finally 块中编写的语句总是会执行。最后，该块适合于关闭文件或数据库连接，确保您不会因为打开文件而出现任何内存错误，也不会因为打开连接或最大连接错误而出现数据库错误。它还确保代码中发生的任何错误都能得到妥善处理。

**语法:**

<small>网页开发、编程语言、软件测试&其他</small>

```
try {
//block of code that may cause an exception
}
```

```
catch {
//Handling the error occurred in try block
}
```

```
finally {
//code that should always execute
}
```

### 如何在 Java 中工作？

这里我们将抛出一个错误或编写一个错误的代码，这将导致一个错误并最终阻塞执行。

**代码:**

```
class ExampleFinally
{
public static void main(String args[]) {
try{
int result = 1/0;
System.out.println(result);
catch(ArithmeticException e){
System.out.println("Divide by Zero Error");
}
/* Finally block will always execute
* even when we have created an error
Block */
finally{
System.out.println("Gracefully Handling Error in Finally");
}
System.out.println("Execution complete out of Try Catch Finally block");
}
}
```

**输出:**

![finally in java 1](../Images/0bc706969b6caf8664bb27723aaae3b9.png)

<noscript><img class="alignnone wp-image-321521 size-full" src="../Images/0bc706969b6caf8664bb27723aaae3b9.png" alt="finally in java 1" width="764" height="132" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/03/finally-in-java-1-1.jpg 764w, https://cdn.educba.com/academy/wp-content/uploads/2020/03/finally-in-java-1-1-300x52.jpg 300w" sizes="(max-width: 764px) 100vw, 764px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/03/finally-in-java-1-1.jpg"/></noscript>

**说明:**

在上面的程序中，我们已经把一个数从零开始除尽了。

*   最终优雅地处理错误。

在 try catch finally，block 之后，我们在打印的所有内容之外写了一段代码。

*   Try Catch Finally 块之外的执行完成。

另一个例子是，我们将看到在 try-catch-finally 块中不会出现异常，并看到会发生什么。

**代码:**

```
class ExampleFinally
{
public static void main(String args[]) {
try
{  int result = 100/10;
System.out.println(result);
System.out.println("try code block");
}
catch (Exception e)
{
System.out.println("catch code block");
}
finally
{
System.out.println("finally code block");
}
}
}
```

**输出:**

![finally in java 2](../Images/77b858abf839179b3c7ac6c350fb8951.png)

<noscript><img class="alignnone wp-image-321522 size-full" src="../Images/77b858abf839179b3c7ac6c350fb8951.png" alt="finally in java 2" width="772" height="134" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/03/finally-in-java-2-1.jpg 772w, https://cdn.educba.com/academy/wp-content/uploads/2020/03/finally-in-java-2-1-300x52.jpg 300w, https://cdn.educba.com/academy/wp-content/uploads/2020/03/finally-in-java-2-1-768x133.jpg 768w" sizes="(max-width: 772px) 100vw, 772px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/03/finally-in-java-2-1.jpg"/></noscript>

**说明:**

在上面的程序中，我们没有编写任何可能导致错误的代码。代码在 try 块中成功执行，但是您仍然可以看到 finally 块被执行并在其中打印了消息。

*   最终代码块

### 最后，Java 程序中的块用法

打开一个文件来读或写需要打开一个文件，然后缓冲流，我们应该确保关闭打开的文件，这样我们就不会得到任何文件处理，IO 或磁盘错误。

**代码:**

```
import java.io.*;
public class ReadingFromFile
{
public static void main(String[] args)throws Exception
{
FileReader fr = null;
try {
fr = new FileReader("/Users/cdp/Documents/testing/python virtual/java/myfile.txt");<>
System.out.println("Opening the file");
BufferedReader br = new BufferedReader(fr);
String line;
while ((line = br.readLine()) != null)
System.out.println(line);
} catch (FileNotFoundException e) {
e.printStackTrace();
} finally {
if (fr != null) {
try {
System.out.println("Closing the file ");
fr.close();
} catch (IOException e) {
System.out.println("unrecoverable Error occurred");
e.printStackTrace();
}
}
System.out.println("Exiting Finally block");
}
}
}
```

**输出(文件不存在):**

![file does not exist](../Images/e6166c64feff53b9a633d106c1607849.png)

<noscript><img class="alignnone wp-image-321523 size-full" src="../Images/e6166c64feff53b9a633d106c1607849.png" alt="file does not exist" width="747" height="139" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/03/finally-in-java-3-1.jpg 747w, https://cdn.educba.com/academy/wp-content/uploads/2020/03/finally-in-java-3-1-300x56.jpg 300w" sizes="(max-width: 747px) 100vw, 747px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/03/finally-in-java-3-1.jpg"/></noscript>

**输出(文件存在):**

![finally in java 4](../Images/58e470bd5d918c265c1ad34679968ab5.png)

<noscript><img class="alignnone wp-image-321524 size-full" src="../Images/58e470bd5d918c265c1ad34679968ab5.png" alt="finally in java 4" width="424" height="99" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/03/finally-in-java-4-1.jpg 424w, https://cdn.educba.com/academy/wp-content/uploads/2020/03/finally-in-java-4-1-300x70.jpg 300w" sizes="(max-width: 424px) 100vw, 424px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/03/finally-in-java-4-1.jpg"/></noscript>

在上面的例子中，我们试图打开一个文件，并从一个文件路径将它读入缓冲区。如果文件存在，并且我们能够读取该文件，那么就不会抛出错误，并且文件缓冲区会在 finally 块中关闭，如果它不是 null 的话。即使在读取文件时有错误，比方说因为某些权限，然后也在最后阻止文件被关闭。

### 意义

*   最后，块必须总是与 try 块相关联；如果没有 try 块，我们就不能编写 use finally 块。你在 finally 块中写的语句会被执行，无论错误发生与否，都不依赖于 try 块代码。
*   最后，该块不是强制块；我们可以编写没有 finally 块的 try 和 catch 块。假设我们只想捕捉任何有问题的用户输入的错误。
*   在没有任何错误发生的情况下，最后，该块将被执行。如果有任何错误，则执行第一个 catch 块，然后最后执行。
*   所有的异常在 finally 块中都有相同的行为。对于所有异常，该块都将正常执行。
*   最后，即使 try 块中有 break、return 或 continue 语句，该块也会执行。

### 最后什么时候不会执行？

到目前为止，我们已经看到了最终块何时以及如何被执行。

但是在某些情况下，这个块最终不会被执行。

*   可能会有一个线程被执行；它很可能是执行程序的主线程，突然它就死了，那么 finally 块就不会被执行了。
*   如果在 try 或 catch 块中，我们使用了带有退出方法 System.exit()的 System 类，那么整个系统都将退出，并且不会将任何控制转移到下一个代码块。
*   如果最终只抛出一个异常，那么程序不会优雅地退出，而是突然退出。

**举例:**

```
import java.io.*;
public class ReadingFromFile
{
public static void main(String[] args)throws Exception
{
FileReader fr = null;
try {
fr = new FileReader("/Users/cdp/Documents/testing/python virtual/java/myfile.txt");
System.out.println("Opening the file");
BufferedReader br = new BufferedReader(fr);
String line;
while ((line = br.readLine()) != null)
System.out.println(line);
System.exit(0);
} catch (FileNotFoundException e) {
e.printStackTrace();
} finally {
if (fr != null) {
try {
System.out.println("Closing the file ");
fr.close();
} catch (IOException e) {
System.out.println("unrecoverable Error occurred");
e.printStackTrace();
}
}
System.out.println("Exiting Finally block");
}
}
}
```

**输出:**

![Example 5](../Images/72358c97ea706607616994908ddb9766.png)

<noscript><img class="alignnone wp-image-321526 size-full" src="../Images/72358c97ea706607616994908ddb9766.png" alt="Example 5" width="345" height="105" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/03/finally-in-java-5-1.jpg 345w, https://cdn.educba.com/academy/wp-content/uploads/2020/03/finally-in-java-5-1-300x91.jpg 300w" sizes="(max-width: 345px) 100vw, 345px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/03/finally-in-java-5-1.jpg"/></noscript>

在上面的例子中，我们在读取文件后，在 try 块中使用了 System.exit，并执行它。如果 System.exit 在没有任何异常的情况下被执行，那么就不会有任何控制转移到 finally 块。但是，如果异常发生在 System.exit 之前，那么 finally 块肯定会被执行。

### 结论

在我们可以得出的结论中，它最终可以在出错时优雅地退出程序中发挥非常重要的作用。最后，当你打开一个连接或缓冲一些东西时，块是很重要的，关闭连接或打开的文件总是很重要的。最后，如果 try 块代码中有错误或没有错误，该块甚至会执行。最后，块不是强制性的，但在某些情况下是有用的。

### 推荐文章

这是一个 Java 中的 Finally 指南。这里我们讨论 Java 中 finally 的介绍，并举例说明在 Java 程序中的用法。您也可以看看以下文章，了解更多信息–

1.  [Java 中的函数重载](https://www.educba.com/function-overloading-in-java/)
2.  [最后在 JavaScript 中](https://www.educba.com/finally-in-javascript/)
3.  [Java 中的 trim()函数](https://www.educba.com/trim-function-in-java/)
4.  [Java LocalDateTime](https://www.educba.com/java-localdatetime/)

<footer class="entry-footer">

<aside class="sidebar sidebar-primary widget-area" role="complementary" aria-label="Primary Sidebar">Primary Sidebar</aside>

</footer>