# Python NameError

> 原文:[https://www.educba.com/python-nameerror/](https://www.educba.com/python-nameerror/)

![Python NameError](../Images/ece20469bcaddf0b9bce7fb8e43c6bd0.png)

<noscript><img class="alignnone size-full wp-image-389470" src="../Images/ece20469bcaddf0b9bce7fb8e43c6bd0.png" alt="Python NameError" width="900" height="500" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/07/Python-NameError.jpg 900w, https://cdn.educba.com/academy/wp-content/uploads/2020/07/Python-NameError-300x167.jpg 300w, https://cdn.educba.com/academy/wp-content/uploads/2020/07/Python-NameError-768x427.jpg 768w" sizes="(max-width: 900px) 100vw, 900px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/07/Python-NameError.jpg"/></noscript>

## Python 名称简介错误

以下文章提供了 Python NameError 的概要。NameError 是 python 中的一种错误，它发生在执行没有引号的函数、变量、库或字符串时，这些引号是在没有任何声明的情况下在代码中键入的。当解释器在执行时不能识别全局或局部名称时，它抛出一个 NameError。可以在错误消息的最后一行查看以了解名称错误，其中未声明的函数、变量、包或字符串将显示在消息中，说明相应的函数、包、变量“未定义”。

### Python 名称的语法错误

在编写一个有名字的函数时，我们经常会在以后错过调用确切的函数名，这将导致一个 NameError。

<small>网页开发、编程语言、软件测试&其他</small>

**举例:**

**代码:**

```
## Functions which return values
def calc_sum(x,y):
    op = x + y
    return(op)

ss = calc_sum(5,10)
print(ss) 
```

**输出:**

**![Python NameError 1](../Images/c3c1850546ab9ce006b8926d33d8ba94.png)

<noscript><img class="alignnone size-full wp-image-388994" src="../Images/c3c1850546ab9ce006b8926d33d8ba94.png" alt="Python NameError 1" width="93" height="47" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/07/Python-NameError-1.jpg"/></noscript>** 

对于同一个函数，让我们看看 NameError。

**代码:**

```
## Functions which return values
def calc_sum(x,y):
    op = x + y
    return(op)

ss = calc_su(5,10)
print(ss) 
```

**输出:**

![Python NameError 2](../Images/a8c97ef46f3b7194bc8103ad6278e54b.png)

<noscript><img class="alignnone wp-image-388995 size-full" src="../Images/a8c97ef46f3b7194bc8103ad6278e54b.png" alt="Python NameError 2" width="458" height="121" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/07/Python-NameError-2.jpg 458w, https://cdn.educba.com/academy/wp-content/uploads/2020/07/Python-NameError-2-300x79.jpg 300w" sizes="(max-width: 458px) 100vw, 458px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/07/Python-NameError-2.jpg"/></noscript>

最初编写它是为了在两个数字之间执行一些运算，并将其命名为 calc_sum，但是在调用它时，我们使用了名称 calc_su，因此它没有在前面定义，它将抛出一个 NameError。

### NameError 如何工作？

当在编码中使用用户定义的变量时，由于解释器很难识别局部/全局值，经常会出现命名错误。

**举例:**

**代码:**

```
l1 = [1,2,5,8,9]
l2 = [1,5.6,"hello"] # mix of data types
l1[1] = 100 # muting the 1<sup>st</sup> position of l1 to 100
print(l1)
del l1[2] # delete from a position 2
print(l1)
```

**输出:**

![Python NameError 3](../Images/7fe28b166163b6ccf7cbfd822f318409.png)

<noscript><img class="alignnone size-full wp-image-388996" src="../Images/7fe28b166163b6ccf7cbfd822f318409.png" alt="Python NameError 3" width="217" height="66" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/07/Python-NameError-3.jpg"/></noscript>

**代码:**

```
l1 = [1,2,5,8,9]
l2 = [1,5.6,"hello"] # mix of data types
l1[1] = 100 # muting the 1<sup>st</sup> position of l1 to 100
print(l1)
del l[2] # delete from a position 2
```

这里我们对一个没有定义的变量 l 执行删除操作。

只定义了 l1 和 l2，解释器只能识别 l1 和 l2 变量。所以如果我们在 l 上操作，它没有被定义，它会抛出一个 NameError。

**输出:**

![Python NameError 4](../Images/6df840d60e35a2aaad46f991b4549a74.png)

<noscript><img class="alignnone wp-image-388997 size-full" src="../Images/6df840d60e35a2aaad46f991b4549a74.png" alt="Python NameError 4" width="447" height="145" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/07/Python-NameError-4.jpg 447w, https://cdn.educba.com/academy/wp-content/uploads/2020/07/Python-NameError-4-300x97.jpg 300w" sizes="(max-width: 447px) 100vw, 447px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/07/Python-NameError-4.jpg"/></noscript>

在使用 python 库或包进行操作的过程中，有时也会出现名称错误。如果我们错过了导入包或库，或者如果我们没有定义包或库的名称，在使用该库执行操作时，我们将得到一个名称错误

**举例:**

**代码:**

```
l10 = [1,2,6,7,4,5,7,8,6,3]
l11 = [1,2,6,7,4,5,7,8,6,3,1000]
## numpy operations
np.mean(l11)
np.median(l11)
np.std(l11)
```

**输出:**

![Python NameError 5](../Images/418b9ee49974290c2b9709b2f24a1031.png)

<noscript><img class="alignnone wp-image-388998 size-full" src="../Images/418b9ee49974290c2b9709b2f24a1031.png" alt="Python NameError 5" width="425" height="123" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/07/Python-NameError-5.jpg 425w, https://cdn.educba.com/academy/wp-content/uploads/2020/07/Python-NameError-5-300x87.jpg 300w" sizes="(max-width: 425px) 100vw, 425px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/07/Python-NameError-5.jpg"/></noscript>

我们没有将 numpy 库作为 np 导入，在执行操作时，我们会看到 NameError。

**代码:**

```
import numpy as np
l10 = [1,2,6,7,4,5,7,8,6,3]
l11 = [1,2,6,7,4,5,7,8,6,3,1000]
## numpy operations
print(np.mean(l11))
print(np.median(l11))
print(np.std(l11))
```

**输出:**

![Python NameError 6](../Images/74d42a38788dae1e812507ca8496bd74.png)

<noscript><img class="alignnone size-full wp-image-388999" src="../Images/74d42a38788dae1e812507ca8496bd74.png" alt="Python NameError 6" width="210" height="100" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/07/Python-NameError-6.jpg"/></noscript>

另一种类型的名称错误发生在我们未能在引号内插入一个字符串值时，解释器将其识别为一个变量并抛出一个名称错误。

**举例:**

**代码:**

```
print('Its a Beautiful day')
name=('Bala')
print(name,'Its a Beautiful day')
```

**输出:**

![Python NameError 7](../Images/c04f7f95dbb1bc8b840b7458e7ace88c.png)

<noscript><img class="alignnone size-full wp-image-389000" src="../Images/c04f7f95dbb1bc8b840b7458e7ace88c.png" alt="Python NameError 7" width="292" height="77" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/07/Python-NameError-7.jpg"/></noscript>

**代码:**

```
Error,
print('Its a Beautiful day')
name=(Bala)
print(name,'Its a Beautiful day')
```

这里我们没有将字符串放在引号内，所以控制台会抛出 NameError。

**输出:**

![fail to put the string inside the quotes](../Images/612f4943f71a2607a3fd1611b120ab77.png)

<noscript><img class="alignnone wp-image-389001 size-full" src="../Images/612f4943f71a2607a3fd1611b120ab77.png" alt="fail to put the string inside the quotes" width="427" height="147" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/07/Python-NameError-8.jpg 427w, https://cdn.educba.com/academy/wp-content/uploads/2020/07/Python-NameError-8-300x103.jpg 300w" sizes="(max-width: 427px) 100vw, 427px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/07/Python-NameError-8.jpg"/></noscript>

### 避免 Python 中的名称错误

通过使用 Python 错误处理技术或异常处理，可以很容易地避免 NameError，这向用户表明代码块中发生了 NameError，而实际上并没有抛出错误。

python 中最常见的错误是语法错误& NameError。当我们编写代码时，如果编程语言不接受它，就会出现语法错误。语法错误可以通过以解释器可以理解的方式遵循编程语言指南来纠正。可以通过使用一种叫做异常处理的技术来避免命名错误。

**代码:**

```
def my_func():
    x="Name Error Exception"
    print(y)
my_func() 
```

**输出:**

![Python NameError 9](../Images/df6187dfe2c7c7f59e1807fa5d59b77c.png)

<noscript><img class="alignnone wp-image-389003 size-full" src="../Images/df6187dfe2c7c7f59e1807fa5d59b77c.png" alt="Python NameError 9" width="428" height="177" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/07/Python-NameError-9.jpg 428w, https://cdn.educba.com/academy/wp-content/uploads/2020/07/Python-NameError-9-300x124.jpg 300w" sizes="(max-width: 428px) 100vw, 428px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/07/Python-NameError-9.jpg"/></noscript>

即使我们编写的代码没有语法错误，程序也会导致运行时错误。这些被称为异常。Python 中有许多内置异常，其中一个是 NameError 异常。

在 Python 中，当我们试图使用或引用一个没有在本地或全局定义的名字时，NameError 异常就会出现。

**举例:**

用于 NameError 异常处理。

**代码:**

```
try:
    x="Name Error Exception"
    print(y)
except NameError:    
    print("Name Error Exception is Caught") 
```

**输出:**

![Exception is caught](../Images/545910634b86376c18250fb3aacb5948.png)

<noscript><img class="alignnone wp-image-389004 size-full" src="../Images/545910634b86376c18250fb3aacb5948.png" alt="Exception is caught" width="351" height="60" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/07/Python-NameError-10.jpg 351w, https://cdn.educba.com/academy/wp-content/uploads/2020/07/Python-NameError-10-300x51.jpg 300w" sizes="(max-width: 351px) 100vw, 351px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/07/Python-NameError-10.jpg"/></noscript>

try 块允许我们检查并查看我们的代码是否会抛出错误。我们可以使用这个块来跟踪我们的代码，看看是否有可能发生错误。

Except 块将允许我们编写想要处理错误的部分。我们可以使用这个块来表示用户在没有控制台抛出错误的情况下出错。

我们还可以将 Finally 块与 try 和 except 一起使用，通过只指示异常消息来不间断地运行代码。

**举例:**

最后，屏蔽。

**代码:**

```
name='Smith'
try:
    print("Hello" " "+ name)
except NameError:
    print("Name is not denoted")
finally:
    print("Have a nice day") 
```

**输出:**

![Finally block](../Images/835bcd5fe39c6144c4536efdf762e480.png)

<noscript><img class="alignnone wp-image-389005 size-full" src="../Images/835bcd5fe39c6144c4536efdf762e480.png" alt="Finally block" width="212" height="77" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/07/Python-NameError-11.jpg"/></noscript>

由于该名称已被指明，代码已成功运行，没有引发异常。下面我们已经删除了表示的名称，我们可以看到抛出的异常消息。

**代码:**

```
name='Smith'
try:
    print("Hello" " "+ name)
except NameError:
    print("Name is not denoted")
finally:
    print("Have a nice day")
    del name    
try:
    print("Hello " + name)
except NameError:
    print("Name is not denoted") 
```

**输出:**

![we can see the exception message thrown](../Images/1d56aeacf375c9cf081df421d44a72d9.png)

<noscript><img class="alignnone wp-image-389006 size-full" src="../Images/1d56aeacf375c9cf081df421d44a72d9.png" alt="we can see the exception message thrown" width="246" height="99" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/07/Python-NameError-12.jpg"/></noscript>

finally 块允许我们在没有终止的情况下运行代码，因为指定的名称被删除了。即使 try 块引发异常消息，finally 块也会被执行。我们可以使用这种技术来克服命名错误。

### 结论

在 python NameError 中要记住的主要问题是解释器无法识别我们在代码中使用的名称或文本。我们已经详细了解了 Python 编程语言中出现的名称错误以及克服名称错误的技术。

### 推荐文章

这是一个 Python 名称错误的指南。在这里，我们分别讨论在 python 中 NameError 是如何工作的以及如何避免 name error。您也可以看看以下文章，了解更多信息–

1.  [Python 输入字符串](https://www.educba.com/python-input-string/)
2.  [Python 字符串操作](https://www.educba.com/python-string-operations/)
3.  [Python 排序列表](https://www.educba.com/python-sort-list/)
4.  [Python 常量](https://www.educba.com/python-constants/)

<footer class="entry-footer">

<aside class="sidebar sidebar-primary widget-area" role="complementary" aria-label="Primary Sidebar">Primary Sidebar</aside>

</footer>